### ISSUE TITLE
Mobile layout on the main page blocks separated by horizontal lines.

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#317]
Website: my-cccp.ru
![ca079bfedd4a4f3ba2bdacc0e9fd104f](https://cloud.githubusercontent.com/assets/3038156/18904394/251158e6-855e-11e6-905f-c4c57602b52a.png)

**Comment by eri-trabiccolo** [comment]
Something like this?
```css
@media only screen and ( max-width: 719px ){
  .post-list .post-row + .post-row .post::before,
  .post-list .post+.post::before {
    border-bottom: 1px solid #eee;
    margin: 30px 0;
    width: 100%;  
  }
  /* reset margin-bottom the margin prop set above will be used */
  .archive .post, .blog .post, .search .page, .search .post, .single .post {
    margin-bottom : 0;
  }
}
```
