### ISSUE TITLE
<code> blocks not formatted in comments

### ISSUE THREAD

**Issue by dhm80** [presscustomizr/hueman#322]
The `<code>`  blocks in entries are formatted well, but this format is missing when placing `<code>`  blocks in comments... It should be something like this:

```css
.comment code,
.entry code {
    background: #eee;
    padding: 0 3px;
}
.comment code,
.entry code,
.entry pre {
    font-family: Monaco, "Courier New", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", monospace;
    font-size: 11px;
}
```
