### ISSUE TITLE
Boxed Non-Responsive Layout Below 1380px Not Working Correctly

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#324]
Global Settings > General Design Options
– Boxed Layout is enabled
– Website Max-width is set to 1200px
Global Settings > Mobile Devices
– Responsive Layout is not enabled

In main-not-responsive.css the .container-inner "max-width" property gets overridden by the dynamic style Max-width but the "min-width" property retains the default of 1380px, resulting in the content being pushed outside the wrapper. If the options Responsive Layout is enabled the page renders correctly.

Reported here:
https://wordpress.org/support/topic/header-and-blog-width-do-not-match/#post-8278355

**Comment by eri-trabiccolo** [comment]
Not sure I'm right, but I see various issue here when disabling the responsive layout.
E.g.
- the behavior @robbinhood mentioned happens even without a boxed layout and without setting a lower website max-width. ( e,g, the container-inner in the #page is wrapped in a .container which has some padding which pushes it to the right, and so on). 
Why the not responsive layout doesn't just care about the  #wrapper width?
Eg.:
```css
/* With some overriding properties - not boxed*/ 
#wrapper { width: 1380px; min-width: 1380px; }
#wrapper .container-inner {min-width: 0;max-width: none; width: 100%;}
```
Then the dynamic width should change accordingly to that.
- Menus still turn into "hamburgers", sidebars .sidebar-top background changes

Mmm, am I missing something?
-
